const MUSCLES = [
  { id: "pectoraux", label: "Pectoraux" },
  { id: "dos", label: "Dos" },
  { id: "epaules", label: "Épaules" },
  { id: "biceps", label: "Biceps" },
  { id: "triceps", label: "Triceps" },
  { id: "jambes", label: "Jambes" },
  { id: "abdos", label: "Abdominaux" },
  { id: "cardio", label: "Cardio" },
];

const DEFAULT_EXOS = [
  // ── PECTORAUX ──────────────────────────────────────────
  { id:"e1",  name:"Développé couché barre",           muscle:"pectoraux", type:"Barre",         level:"medium", video:"https://www.youtube.com/watch?v=rT7DgCr-3pg" },
  { id:"e2",  name:"Développé incliné haltères",        muscle:"pectoraux", type:"Haltères",      level:"medium", video:"https://www.youtube.com/watch?v=8iPEnn-ltC8" },
  { id:"e3",  name:"Développé couché haltères",         muscle:"pectoraux", type:"Haltères",      level:"medium", video:"https://www.youtube.com/watch?v=VmB1G1K7v94" },
  { id:"e4",  name:"Développé décliné barre",           muscle:"pectoraux", type:"Barre",         level:"medium", video:"" },
  { id:"e5",  name:"Développé incliné barre",           muscle:"pectoraux", type:"Barre",         level:"medium", video:"" },
  { id:"e6",  name:"Écarté haltères couché",            muscle:"pectoraux", type:"Haltères",      level:"easy",   video:"https://www.youtube.com/watch?v=eozdVDA78K0" },
  { id:"e7",  name:"Écarté haltères incliné",           muscle:"pectoraux", type:"Haltères",      level:"easy",   video:"" },
  { id:"e8",  name:"Écarté poulie vis-à-vis",           muscle:"pectoraux", type:"Câbles",        level:"easy",   video:"https://www.youtube.com/watch?v=taI4XduLpTk" },
  { id:"e9",  name:"Écarté poulie décliné",             muscle:"pectoraux", type:"Câbles",        level:"easy",   video:"" },
  { id:"e10", name:"Pec deck / Butterfly",              muscle:"pectoraux", type:"Machine",       level:"easy",   video:"https://www.youtube.com/watch?v=Z57CtFmRMxA" },
  { id:"e11", name:"Chest press machine",               muscle:"pectoraux", type:"Machine",       level:"easy",   video:"" },
  { id:"e12", name:"Dips pectoraux",                    muscle:"pectoraux", type:"Poids de corps",level:"medium", video:"https://www.youtube.com/watch?v=2z8JmcrW-As" },
  { id:"e13", name:"Pompes",                            muscle:"pectoraux", type:"Poids de corps",level:"easy",   video:"https://www.youtube.com/watch?v=IODxDxX7oi4" },
  { id:"e14", name:"Pompes inclinées",                  muscle:"pectoraux", type:"Poids de corps",level:"easy",   video:"" },
  { id:"e15", name:"Pompes déclinées",                  muscle:"pectoraux", type:"Poids de corps",level:"medium", video:"" },
  { id:"e16", name:"Pompes diamant",                    muscle:"pectoraux", type:"Poids de corps",level:"medium", video:"" },
  { id:"e17", name:"Chest press sangles TRX",           muscle:"pectoraux", type:"Poids de corps",level:"medium", video:"" },
  { id:"e18", name:"Développé couché prise serrée",     muscle:"pectoraux", type:"Barre",         level:"medium", video:"" },
  { id:"e19", name:"Pullover haltère",                  muscle:"pectoraux", type:"Haltères",      level:"medium", video:"https://www.youtube.com/watch?v=FK4rHfHHBkI" },

  // ── DOS ───────────────────────────────────────────────
  { id:"e20", name:"Tractions prise large",             muscle:"dos", type:"Poids de corps",level:"hard",   video:"https://www.youtube.com/watch?v=eGo4IYlbE5g" },
  { id:"e21", name:"Tractions prise neutre",            muscle:"dos", type:"Poids de corps",level:"hard",   video:"" },
  { id:"e22", name:"Tractions supination",              muscle:"dos", type:"Poids de corps",level:"hard",   video:"" },
  { id:"e23", name:"Tractions australiennes",           muscle:"dos", type:"Poids de corps",level:"medium", video:"" },
  { id:"e24", name:"Rowing barre",                      muscle:"dos", type:"Barre",         level:"medium", video:"https://www.youtube.com/watch?v=FWJR5Ve8bnQ" },
  { id:"e25", name:"Rowing barre prise supination",     muscle:"dos", type:"Barre",         level:"medium", video:"" },
  { id:"e26", name:"Rowing haltère unilatéral",         muscle:"dos", type:"Haltères",      level:"medium", video:"https://www.youtube.com/watch?v=roCP0_vs3tk" },
  { id:"e27", name:"Rowing assis machine",              muscle:"dos", type:"Machine",       level:"easy",   video:"" },
  { id:"e28", name:"Rowing à la Smith machine",         muscle:"dos", type:"Machine",       level:"medium", video:"" },
  { id:"e29", name:"Tirage vertical prise large",       muscle:"dos", type:"Machine",       level:"easy",   video:"https://www.youtube.com/watch?v=CAwf7n6Luuc" },
  { id:"e30", name:"Tirage vertical prise serrée",      muscle:"dos", type:"Machine",       level:"easy",   video:"" },
  { id:"e31", name:"Tirage vertical prise neutre",      muscle:"dos", type:"Machine",       level:"easy",   video:"" },
  { id:"e32", name:"Tirage poitrine prise large",       muscle:"dos", type:"Machine",       level:"easy",   video:"" },
  { id:"e33", name:"Tirage horizontal câbles",          muscle:"dos", type:"Câbles",        level:"easy",   video:"https://www.youtube.com/watch?v=GZbfZ033f74" },
  { id:"e34", name:"Tirage horizontal élastique",       muscle:"dos", type:"Poids de corps",level:"easy",   video:"" },
  { id:"e35", name:"Soulevé de terre",                  muscle:"dos", type:"Barre",         level:"hard",   video:"https://www.youtube.com/watch?v=op9kVnSso6Q" },
  { id:"e36", name:"Soulevé de terre jambes tendues",   muscle:"dos", type:"Barre",         level:"hard",   video:"" },
  { id:"e37", name:"Shrug barre",                       muscle:"dos", type:"Barre",         level:"easy",   video:"" },
  { id:"e38", name:"Shrug haltères",                    muscle:"dos", type:"Haltères",      level:"easy",   video:"" },
  { id:"e39", name:"Pull-over machine",                 muscle:"dos", type:"Machine",       level:"easy",   video:"" },
  { id:"e40", name:"Superman",                          muscle:"dos", type:"Poids de corps",level:"easy",   video:"" },
  { id:"e41", name:"Good morning",                      muscle:"dos", type:"Barre",         level:"medium", video:"" },

  // ── ÉPAULES ───────────────────────────────────────────
  { id:"e42", name:"Développé militaire barre",         muscle:"epaules", type:"Barre",     level:"medium", video:"https://www.youtube.com/watch?v=2yjwXTZQDDI" },
  { id:"e43", name:"Développé militaire haltères",      muscle:"epaules", type:"Haltères",  level:"medium", video:"" },
  { id:"e44", name:"Arnold press",                      muscle:"epaules", type:"Haltères",  level:"medium", video:"https://www.youtube.com/watch?v=-ioXhOkRDOo" },
  { id:"e45", name:"Élévations latérales haltères",     muscle:"epaules", type:"Haltères",  level:"easy",   video:"https://www.youtube.com/watch?v=3VcKaXpzqRo" },
  { id:"e46", name:"Élévations latérales poulie",       muscle:"epaules", type:"Câbles",    level:"easy",   video:"" },
  { id:"e47", name:"Élévations frontales haltères",     muscle:"epaules", type:"Haltères",  level:"easy",   video:"" },
  { id:"e48", name:"Élévations frontales poulie",       muscle:"epaules", type:"Câbles",    level:"easy",   video:"" },
  { id:"e49", name:"Face pull",                         muscle:"epaules", type:"Câbles",    level:"easy",   video:"https://www.youtube.com/watch?v=rep-qVOkqgk" },
  { id:"e50", name:"Oiseau haltères (élévations 45°)",  muscle:"epaules", type:"Haltères",  level:"easy",   video:"" },
  { id:"e51", name:"Oiseau poulie",                     muscle:"epaules", type:"Câbles",    level:"easy",   video:"" },
  { id:"e52", name:"Reverse fly machine",               muscle:"epaules", type:"Machine",   level:"easy",   video:"" },
  { id:"e53", name:"Tirage menton barre",               muscle:"epaules", type:"Barre",     level:"medium", video:"" },
  { id:"e54", name:"Tirage menton câbles",              muscle:"epaules", type:"Câbles",    level:"medium", video:"" },
  { id:"e55", name:"Développé épaules machine",         muscle:"epaules", type:"Machine",   level:"easy",   video:"" },
  { id:"e56", name:"Pompes piquées",                    muscle:"epaules", type:"Poids de corps",level:"medium",video:"" },
  { id:"e57", name:"Élévations Y à la poulie",          muscle:"epaules", type:"Câbles",    level:"easy",   video:"" },

  // ── BICEPS ────────────────────────────────────────────
  { id:"e58", name:"Curl barre droite",                 muscle:"biceps", type:"Barre",      level:"easy",   video:"https://www.youtube.com/watch?v=ykJmrZ5v0Oo" },
  { id:"e59", name:"Curl barre EZ",                     muscle:"biceps", type:"Barre",      level:"easy",   video:"https://www.youtube.com/watch?v=av7-8igSXTs" },
  { id:"e60", name:"Curl haltères alterné",             muscle:"biceps", type:"Haltères",   level:"easy",   video:"https://www.youtube.com/watch?v=sAq_ocpRh_I" },
  { id:"e61", name:"Curl haltères simultané",           muscle:"biceps", type:"Haltères",   level:"easy",   video:"" },
  { id:"e62", name:"Curl marteau",                      muscle:"biceps", type:"Haltères",   level:"easy",   video:"https://www.youtube.com/watch?v=TwD-YGVP4Bk" },
  { id:"e63", name:"Curl concentré",                    muscle:"biceps", type:"Haltères",   level:"easy",   video:"" },
  { id:"e64", name:"Curl incliné haltères",             muscle:"biceps", type:"Haltères",   level:"easy",   video:"" },
  { id:"e65", name:"Curl araignée (spider curl)",       muscle:"biceps", type:"Haltères",   level:"medium", video:"" },
  { id:"e66", name:"Curl Zottman",                      muscle:"biceps", type:"Haltères",   level:"medium", video:"" },
  { id:"e67", name:"Curl prise inverse",                muscle:"biceps", type:"Barre",      level:"easy",   video:"" },
  { id:"e68", name:"Curl poulie basse",                 muscle:"biceps", type:"Câbles",     level:"easy",   video:"" },
  { id:"e69", name:"Curl poulie basse prise neutre",    muscle:"biceps", type:"Câbles",     level:"easy",   video:"" },
  { id:"e70", name:"Curl au pupitre barre EZ",          muscle:"biceps", type:"Barre",      level:"easy",   video:"https://www.youtube.com/watch?v=fIWP-FRFNU0" },
  { id:"e71", name:"Curl machine",                      muscle:"biceps", type:"Machine",    level:"easy",   video:"" },
  { id:"e72", name:"Tractions supination (biceps)",     muscle:"biceps", type:"Poids de corps",level:"hard", video:"" },

  // ── TRICEPS ───────────────────────────────────────────
  { id:"e73", name:"Dips triceps",                      muscle:"triceps", type:"Poids de corps",level:"medium",video:"https://www.youtube.com/watch?v=2z8JmcrW-As" },
  { id:"e74", name:"Dips sur banc",                     muscle:"triceps", type:"Poids de corps",level:"easy",  video:"" },
  { id:"e75", name:"Extension barre au front",          muscle:"triceps", type:"Barre",     level:"medium", video:"https://www.youtube.com/watch?v=d_KZxkY_0cM" },
  { id:"e76", name:"Extension barre EZ au front",       muscle:"triceps", type:"Barre",     level:"medium", video:"" },
  { id:"e77", name:"Extension haltère unilatérale",     muscle:"triceps", type:"Haltères",  level:"easy",   video:"" },
  { id:"e78", name:"Extension nuque haltère",           muscle:"triceps", type:"Haltères",  level:"easy",   video:"https://www.youtube.com/watch?v=YbX7Wd8jQ-Q" },
  { id:"e79", name:"Extension nuque câbles",            muscle:"triceps", type:"Câbles",    level:"easy",   video:"" },
  { id:"e80", name:"Pushdown poulie corde",             muscle:"triceps", type:"Câbles",    level:"easy",   video:"https://www.youtube.com/watch?v=vB5OHsJ3EME" },
  { id:"e81", name:"Pushdown poulie barre",             muscle:"triceps", type:"Câbles",    level:"easy",   video:"" },
  { id:"e82", name:"Pushdown poulie prise inversée",    muscle:"triceps", type:"Câbles",    level:"easy",   video:"" },
  { id:"e83", name:"Kickback haltère",                  muscle:"triceps", type:"Haltères",  level:"easy",   video:"" },
  { id:"e84", name:"Extension triceps machine",         muscle:"triceps", type:"Machine",   level:"easy",   video:"" },
  { id:"e85", name:"Extension triceps en suspension",   muscle:"triceps", type:"Poids de corps",level:"medium",video:"" },
  { id:"e86", name:"Pompes diamant triceps",            muscle:"triceps", type:"Poids de corps",level:"medium",video:"" },
  { id:"e87", name:"Développé couché prise serrée",     muscle:"triceps", type:"Barre",     level:"medium", video:"" },

  // ── JAMBES ────────────────────────────────────────────
  { id:"e88", name:"Squat barre",                       muscle:"jambes", type:"Barre",      level:"hard",   video:"https://www.youtube.com/watch?v=ultWZbUMPL8" },
  { id:"e89", name:"Squat gobelet",                     muscle:"jambes", type:"Haltères",   level:"medium", video:"" },
  { id:"e90", name:"Squat hack",                        muscle:"jambes", type:"Machine",    level:"medium", video:"" },
  { id:"e91", name:"Squat Smith machine",               muscle:"jambes", type:"Machine",    level:"medium", video:"" },
  { id:"e92", name:"Presse à cuisses",                  muscle:"jambes", type:"Machine",    level:"medium", video:"https://www.youtube.com/watch?v=IZxyjW7MPJQ" },
  { id:"e93", name:"Fentes barre",                      muscle:"jambes", type:"Barre",      level:"medium", video:"" },
  { id:"e94", name:"Fentes haltères",                   muscle:"jambes", type:"Haltères",   level:"medium", video:"https://www.youtube.com/watch?v=D7KaRcUTQeE" },
  { id:"e95", name:"Fentes marchées haltères",          muscle:"jambes", type:"Haltères",   level:"medium", video:"" },
  { id:"e96", name:"Bulgarian split squat",             muscle:"jambes", type:"Haltères",   level:"hard",   video:"" },
  { id:"e97", name:"Leg extension",                     muscle:"jambes", type:"Machine",    level:"easy",   video:"https://www.youtube.com/watch?v=YyvSfVjQeL0" },
  { id:"e98", name:"Leg curl allongé",                  muscle:"jambes", type:"Machine",    level:"easy",   video:"https://www.youtube.com/watch?v=1Tq3QdYUuHs" },
  { id:"e99", name:"Leg curl assis",                    muscle:"jambes", type:"Machine",    level:"easy",   video:"" },
  { id:"e100",name:"Romanian deadlift",                 muscle:"jambes", type:"Barre",      level:"hard",   video:"https://www.youtube.com/watch?v=JCXUYuzwNrM" },
  { id:"e101",name:"Soulevé de terre sumo",             muscle:"jambes", type:"Barre",      level:"hard",   video:"" },
  { id:"e102",name:"Hip thrust barre",                  muscle:"jambes", type:"Barre",      level:"medium", video:"https://www.youtube.com/watch?v=SEdqd1n0cvg" },
  { id:"e103",name:"Hip thrust machine",                muscle:"jambes", type:"Machine",    level:"medium", video:"" },
  { id:"e104",name:"Mollets debout machine",            muscle:"jambes", type:"Machine",    level:"easy",   video:"" },
  { id:"e105",name:"Mollets assis machine",             muscle:"jambes", type:"Machine",    level:"easy",   video:"" },
  { id:"e106",name:"Mollets presse à cuisses",          muscle:"jambes", type:"Machine",    level:"easy",   video:"" },
  { id:"e107",name:"Glute kickback machine",            muscle:"jambes", type:"Machine",    level:"easy",   video:"" },
  { id:"e108",name:"Adducteurs machine",                muscle:"jambes", type:"Machine",    level:"easy",   video:"" },
  { id:"e109",name:"Abducteurs machine",                muscle:"jambes", type:"Machine",    level:"easy",   video:"" },

  // ── ABDOMINAUX ────────────────────────────────────────
  { id:"e110",name:"Crunch",                            muscle:"abdos", type:"Poids de corps",level:"easy",  video:"https://www.youtube.com/watch?v=Xyd_fa5zoEU" },
  { id:"e111",name:"Crunch bicyclette",                 muscle:"abdos", type:"Poids de corps",level:"easy",  video:"" },
  { id:"e112",name:"Crunch papillon",                   muscle:"abdos", type:"Poids de corps",level:"easy",  video:"" },
  { id:"e113",name:"Crunch latéral",                    muscle:"abdos", type:"Poids de corps",level:"easy",  video:"" },
  { id:"e114",name:"Crunch poulie haute",               muscle:"abdos", type:"Câbles",      level:"medium", video:"" },
  { id:"e115",name:"Planche frontale",                  muscle:"abdos", type:"Poids de corps",level:"medium",video:"https://www.youtube.com/watch?v=pSHjTRCQxIw" },
  { id:"e116",name:"Planche latérale",                  muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e117",name:"Planche inversée",                  muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e118",name:"Relevé de jambes suspendu",         muscle:"abdos", type:"Poids de corps",level:"hard",  video:"" },
  { id:"e119",name:"Relevé de jambes à la chaise romaine",muscle:"abdos",type:"Poids de corps",level:"hard", video:"" },
  { id:"e120",name:"Ab wheel (roue abdominale)",        muscle:"abdos", type:"Poids de corps",level:"hard",  video:"https://www.youtube.com/watch?v=q3VrFjPQ-jU" },
  { id:"e121",name:"Mountain climber",                  muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e122",name:"Ciseaux",                           muscle:"abdos", type:"Poids de corps",level:"easy",  video:"" },
  { id:"e123",name:"V-up",                              muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e124",name:"Dragon flag",                       muscle:"abdos", type:"Poids de corps",level:"hard",  video:"" },
  { id:"e125",name:"Rotation russe",                    muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e126",name:"Touches talons alternées",          muscle:"abdos", type:"Poids de corps",level:"easy",  video:"" },
  { id:"e127",name:"Cocon",                             muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e128",name:"Jackknife sur swiss ball",          muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e129",name:"Gainage latéral dynamique",         muscle:"abdos", type:"Poids de corps",level:"medium",video:"" },
  { id:"e130",name:"Ab crunch machine",                 muscle:"abdos", type:"Machine",     level:"easy",   video:"" },
  { id:"e131",name:"Planche chinoise",                  muscle:"abdos", type:"Poids de corps",level:"hard",  video:"" },

  // ── CARDIO ────────────────────────────────────────────
  { id:"e132",name:"Course tapis roulant",              muscle:"cardio", type:"Cardio",     level:"easy",   video:"" },
  { id:"e133",name:"Vélo elliptique",                   muscle:"cardio", type:"Cardio",     level:"easy",   video:"" },
  { id:"e134",name:"Rameur",                            muscle:"cardio", type:"Cardio",     level:"medium", video:"" },
  { id:"e135",name:"Corde à sauter",                    muscle:"cardio", type:"Cardio",     level:"medium", video:"" },
  { id:"e136",name:"Vélo stationnaire",                 muscle:"cardio", type:"Cardio",     level:"easy",   video:"" },
  { id:"e137",name:"Burpees",                           muscle:"cardio", type:"Poids de corps",level:"hard", video:"" },
  { id:"e138",name:"Jumping jacks",                     muscle:"cardio", type:"Poids de corps",level:"easy", video:"" },
  { id:"e139",name:"Battle ropes",                      muscle:"cardio", type:"Poids de corps",level:"hard", video:"" },
  { id:"e140",name:"Box jump",                          muscle:"cardio", type:"Poids de corps",level:"medium",video:"" },
];
